App\Entity\User:
  attributes:
    normalization_context:
      groups: [user_read]
  collectionOperations:
    create:
      method: POST
      path: /users/create
      controller: App\Api\Action\User\Create
      denormalization_context:
        groups: [user_post]
      openapi_context:
        summary: Create a new user
  itemOperations:
    get:
      method: GET
      
      
